<?php

namespace Common;

use Common\Core\Bootstrap\BaseBootstrapData;
use Common\Core\Bootstrap\BootstrapData;
use Common\Core\Commands\SeedCommand;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\ServiceProvider;

class CommonServiceProvider  extends ServiceProvider
{

    public function __construct($app)
    {
        parent::__construct($app);
        $app->instance('path.common', base_path('common'));
    }

    public function boot(){
        $this->registerCommands();
        $this->registerCustomValidators();
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        // bootstrap data
        $this->app->bind(BootstrapData::class, BaseBootstrapData::class);
    }

    private function registerCommands()
    {
        // register commands
        $commands = [
            SeedCommand::class,
        ];

        $this->commands($commands);

    }

    private function registerCustomValidators()
    {
        Validator::extend(
            'email_verified',
            'Common\Auth\Validators\EmailVerifiedValidator@validate',
        );
    }
}
