<?php

namespace App\Providers;

use App\Services\Bootstrap\BaseBootstrapData;
use App\Services\Bootstrap\BootstrapData;
use Common\Core\Commands\SeedCommand;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\ServiceProvider;

class CommonServiceProvider  extends ServiceProvider
{

    public function __construct($app)
    {
        parent::__construct($app);
        $app->instance('path.config', base_path('config'));
    }

    public function boot(){
        $this->registerCustomValidators();
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        // bootstrap data
        $this->app->bind(BootstrapData::class, BaseBootstrapData::class);
    }


    private function registerCustomValidators()
    {
        Validator::extend(
            'email_verified',
            'App\Rules\EmailVerifiedValidator@validate',
        );
    }
}
